[pytest]

testpaths = tests tests_api

python_files = test_*.py

python_classes = Test*

python_functions = test_*

addopts =
    -v
    --strict-markers

markers =
    ui: Browser tests with Playwright
    api: API tests with Python requests
    smoke: Smoke Tests
    e2e: End To End Tests
    negative: Negative Tests
